services:
  db-dev:
    container_name: back-dev-container
    image: mysql:8.0
    volumes:
      - back-dev-volume:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env

volumes:
  db-dev-volume:
